#!/bin/bash

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# User specific environment
if ! [[ "$PATH" =~ "${HOME}/.local/bin" ]]; then
    export PATH="${HOME}/.local/bin:${PATH}"
fi

bash_config_dir="${HOME}/.config/bash"
bashrc_dir="${bash_config_dir}/bashrc.d"

# User specific bashrc.d
if [[ -d ${bashrc_dir} ]]; then
        for rc in ${bashrc_dir}/* ; do
                if [[ -f "$rc" ]]; then
                        source "$rc"
                fi
        done
        unset rc
fi

# Host specific bashrc.d
bashrc_dir_self="${bash_config_dir}/self.d"
if [[ -d ${bashrc_dir_self} ]]; then
        for rc in ${bashrc_dir_self}/* ; do
                if [[ -f "$rc" ]]; then
                        source "$rc"
                fi
        done
        unset rc
fi

unset bash_config_dir
unset bashrc_dir
unset bashrc_dir_self

# RUSTUP
# . "$HOME/.cargo/env"


# NVM
# export NVM_DIR="$HOME/.config/nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
