#!/bin/bash

alias e="${EDITOR}"

alias g="git"

alias myip="curl https://httpbin.org/ip 2> /dev/null | jq -r .origin"

alias gbclear="git branch --merged | egrep -v '(^\*|main|develop|master)' | xargs git branch -d"

alias tma='tmux attach-session -t '

alias l='ls -CF'
alias la='ls -la'
alias ll='ls -alF'
