[colors.bright]
black = "#7f8c8d"
blue = "#3daee9"
cyan = "#16a085"
green = "#1cdc9a"
magenta = "#a96ec2"
red = "#c0392b"
white = "#ffffff"
yellow = "#fdbc4b"

[colors.dim]
black = "#31363b"
blue = "#1b668f"
cyan = "#186c60"
green = "#17a262"
magenta = "#614a73"
red = "#783228"
white = "#63686d"
yellow = "#b65619"

[colors.normal]
black = "#181920"
blue = "#1d99f3"
cyan = "#1abc9c"
green = "#11d116"
magenta = "#9b59b6"
red = "#ed1515"
white = "#fcfcfc"
yellow = "#f67400"

[colors.primary]
background = "#181920"
bright_foreground = "#ffffff"
dim_foreground = "#eff0f1"
foreground = "#fcfcfc"

[font]
size = 10.0

[font.normal]
family = "DejaVuSansMNerdFont"

[[keyboard.bindings]]
chars = "\r"
key = "NumpadEnter"

[mouse]
hide_when_typing = true

[window]
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 128
lines = 56

[window.padding]
x = 6
y = 8
