#!/bin/bash

# ------------------------------------------------------------------------------

RESET=$'\e[0m'
# --
BOLD_BLUE=$'\e[1;34m'
BOLD_MAGENTA=$'\e[1;35m'
BOLD_RED=$'\e[1;31m'
BOLD_YELLOW=$'\e[1;33m'
# --
BLUE=$'\e[34m'
GREEN=$'\e[32m'
YELLOW=$'\e[33m'
YELLOW229=$'\e[38;5;229m'

# ------------------------------------------------------------------------------

# STATUS_GLYPH=$'\u25E5'
# STATUS_GLYPH=$'\u25F9'
STATUS_GLYPH=$'\u25E6'
TERMINAL_GLYPH=$'\uf489'

# ------------------------------------------------------------------------------

user="${USER}"
if [[ "${user}" == "ericelsken" || "${user}" == "eric-elsken" ]]; then
	user="me"
fi

hostname="${HOSTNAME}"
case "${hostname,,}" in
	*ericelsken*|*eric-elsken*|localhost.localdoamin)
		hostname="here"
		;;
esac

userhostname_color="${BLUE}"
if [[ "${user}" != "me" || "${hostname}" != "here" ]]; then
	userhostname_color="${BOLD_MAGENTA}"
fi

# ------------------------------------------------------------------------------

_e2_git_dirty() {
	if [[ -n $(git status --porcelain 2>/dev/null) ]]; then
		printf '*'
	else
		printf ' '
	fi
}

_e2_git_branch() {
	local branch

	branch="$(git branch --show-current 2>/dev/null)"
	if [[ -z "${branch}" ]]; then
		branch="detached:$(git name-rev --name-only HEAD 2>/dev/null)"
	fi

	if [[ -n "${branch}" ]]; then
		printf '%.16s' "${branch}"
		(( ${#branch} > 16 )) && printf '..'
	fi
}

_e2_aws_text() {
	local result

	if [[ -n "${AWS_PROFILE}" ]]; then
		result="${AWS_PROFILE}"
	elif [[ -n "${AWS_VAULT}" ]]; then
		result="${AWS_VAULT}"
	fi

	if [[ -n "${result}" ]]; then
		if (( ${#result} > 8 )); then
			printf '%s..%s' "${result:0:3}" "${result: -3}"
		else
			printf '%s' "${result}"
		fi
	fi
}

# ------------------------------------------------------------------------------

_e2_update_prompt() {
	local exit_code=$?
	local exit_code_color="${BOLD_RED}"
	(( exit_code == 0 )) && exit_code_color="${GREEN}"

	local git_dirty git_branch git_color 
	if git rev-parse --is-inside-work-tree >/dev/null 2>&1 ; then
		git_dirty="$(_e2_git_dirty)"
		git_branch="$(_e2_git_branch)"

		if [[ "${git_branch}" == "main" || "${git_branch}" == "master" ]]; then
			git_color="${BOLD_RED}"
		elif [[ "${git_branch}" == detached:* || "${git_dirty}" == "*" ]]; then
			git_color="${BOLD_YELLOW}"
		elif [[ "${git_branch}" == "develop" ]]; then
			git_color="${BOLD_MAGENTA}"
		else
			git_color="${GREEN}"
		fi
	fi

	local aws_text="$(_e2_aws_text)"

	# --

	PS1="\[${exit_code_color}\]${STATUS_GLYPH} "
	PS1+="\[${RESET}\]"
	PS1+="\[${userhostname_color}\][${user}@${hostname}]"
	PS1+="\[${RESET}\] "
	PS1+="\[${BOLD_BLUE}\]\W"
	PS1+="\[${RESET}\]"

	if [[ -n "${git_branch}" ]]; then
		PS1+="\[${git_color}\] (${git_branch} ${git_dirty})"
	fi

	if [[ -n "${aws_text}" ]]; then
		PS1+="\[${YELLOW}\] [AWS ${aws_text}]"
	fi

	if (( SHLVL > 1 )) && ! [[ -n "${TMUX-}" && "${SHLVL}" -le 2 ]] ; then
		PS1+="\[${YELLOW229}\] ${TERMINAL_GLYPH} ${SHLVL}"
	fi

	PS1+="\[${RESET}\] "
	PS1+="\[${BOLD_BLUE}\]\$"
	PS1+="\[${RESET}\] "
}

PROMPT_COMMAND=_e2_update_prompt
