#!/bin/bash

E2_PLUGINS_DIR="${HOME}/.local/share/e2/plugins"

if ! declare -F _init_completion >/dev/null && [[ -r /usr/share/bash-completion/bash_completion ]]; then
	source /usr/share/bash-completion/bash_completion
fi

_e2_completions() {
	local cur prev words cword
	_init_completion -n : || return

	if [[ "${prev}" == "e2" && "${cword}" -eq 1 ]]; then
		
		local plugins=()
		while IFS='' read -r -d '' p; do
			plugins+=( "$(basename "${p}")" )
		done < <(find "${E2_PLUGINS_DIR}" -maxdepth 1 ! -type d -perm -u+x -print0 2>/dev/null)

		COMPREPLY=( $(compgen -W "${plugins[*]}" -- "${cur}") )
		return 0
	fi

	return 0
}

complete -F _e2_completions e2
